[package]
name = "gbatopy-mgba"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
gbatopy-disasm = { path = "../gbatopy-disasm" }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.8"